language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew test
  - ./gradlew build 
  - ./gradlew run

notifications:
  slack: praxisunal:NOEwF8jyKirLXm8yXdJg4dEw
    on_success: change 
    on_failure: always 
